source 'https://rubygems.org'

gem 'google_drive'
gem 'sinatra'
gem 'pry'
gem 'settingslogic'
gem 'pipedrive-ruby', '~> 0.3.3'
gem 'rest-client'
gem 'peach'
gem 'nokogiri'
gem 'parallel'
gem 'customerio'
gem 'multi_json'
